# Generated by Django 4.2.2 on 2023-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_chatmessage_thread_delete_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='thread',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
