# Generated by Django 4.2.2 on 2023-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_chatmessage_is_read_thread_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
