# Generated by Django 4.2.2 on 2023-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(upload_to='public/community_app//event_images'),
        ),
    ]
