# Generated by Django 4.2.2 on 2023-06-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Events', 'verbose_name_plural': 'Events'},
        ),
    ]
