# Generated by Django 4.2.2 on 2023-07-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_events_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="is_bookmarked",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="is_liked",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
