# Generated by Django 4.2.2 on 2023-07-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_events_event_date_events_is_bookmarked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="event_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
