# Generated by Django 4.2.2 on 2023-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_events_event_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="event_duration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
