# Generated by Django 4.2.2 on 2023-07-11 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0006_alter_events_event_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="is_bookmarked",
        ),
        migrations.RemoveField(
            model_name="events",
            name="is_liked",
        ),
        migrations.AddField(
            model_name="events",
            name="bookmarked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarked_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
