# Generated by Django 4.2.2 on 2023-06-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='member_name',
            new_name='news_title',
        ),
    ]
