# Generated by Django 4.2.2 on 2023-07-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_rename_member_name_news_news_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_reported",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
