# Generated by Django 4.2.2 on 2023-06-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notification_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="notification_content",
            new_name="content",
        ),
    ]
