# Generated by Django 4.2.2 on 2023-06-16 07:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification", "0004_alter_notification_is_read"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notification",
            new_name="SendNotification",
        ),
    ]
