# Generated by Django 4.2.2 on 2023-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_sendnotification_event_sendnotification_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendnotification",
            name="event",
        ),
        migrations.RemoveField(
            model_name="sendnotification",
            name="news",
        ),
        migrations.AddField(
            model_name="sendnotification",
            name="content_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
