# Generated by Django 4.2.2 on 2023-06-16 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pages",
            options={"verbose_name": "Pages", "verbose_name_plural": "Pages"},
        ),
    ]


# Generated by Django 4.2.2 on 2023-06-15 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pages",
            options={"verbose_name": "Pages", "verbose_name_plural": "Pages"},
        ),
    ]
