# Generated by Django 4.2.2 on 2023-06-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
