# Generated by Django 4.2.2 on 2023-06-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
