# Generated by Django 4.2.2 on 2023-06-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currently_living_at',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relation_with_main_member',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
