# Generated by Django 4.2.2 on 2023-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='push_notification',
            field=models.BooleanField(null=True),
        ),
    ]
